apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: emails.stable.email-sender-operator.dev
spec:
  group: stable.email-sender-operator.dev
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              # NOTE: should it be an object?
              type: object
              properties:
                # NOTE: Reference to EmailSenderConfig
                # TODO: Validate?
                senderConfigRef:
                  type: string
                recipientEmail:
                  type: string
                subject:
                  type: string
                body:
                  type: string
            status:
              type: object
              properties:
                deliveryStatus:
                  type: string
                messageId:
                  type: string
  scope: Namespaced
  names:
    plural: emails
    singular: email
    kind: Email
    shortNames:
    - eml
