apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev
  name: email-sender-operator
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      application: email-sender-operator
  template:
    metadata:
      labels:
        application: email-sender-operator
    spec:
      serviceAccountName: email-sender-operator-service-account
      containers:
      - name: email-sender-operator
        image: flavioalles/email-sender-operator:dev # TODO: set to latest for final version
        imagePullPolicy: Always # TODO: remove for final version
