---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: dev
  name: email-sender-operator-service-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: email-sender-operator-role-cluster
rules:

  # Framework: knowing which other operators are running (i.e. peering).
  - apiGroups: [kopf.dev]
    resources: [clusterkopfpeerings]
    verbs: [list, watch, patch, get]

  # Framework: runtime observation of namespaces & CRDs (addition/deletion).
  - apiGroups: [apiextensions.k8s.io]
    resources: [customresourcedefinitions]
    verbs: [list, watch]
  - apiGroups: [""]
    resources: [namespaces]
    verbs: [list, watch]

  # Framework: admission webhook configuration management.
  - apiGroups: [admissionregistration.k8s.io/v1, admissionregistration.k8s.io/v1beta1]
    resources: [validatingwebhookconfigurations, mutatingwebhookconfigurations]
    verbs: [create, patch]

  # Application: read-only access for watching cluster-wide.
  # - apiGroups: [kopf.dev]
  #   resources: [kopfexamples]
  #   verbs: [list, watch]
  - apiGroups: [stable.email-sender-operator.dev]
    resources: [emailsenderconfigs, emails]
    verbs: [list, watch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: dev
  name: email-sender-operator-role
rules:

  # Framework: knowing which other operators are running (i.e. peering).
  - apiGroups: [kopf.dev]
    resources: [kopfpeerings]
    verbs: [list, watch, patch, get]

  # Framework: posting the events about the handlers progress/errors.
  - apiGroups: [""]
    resources: [events]
    verbs: [create]

  # Application: watching & handling for the custom resource we declare.
  - apiGroups: [stable.email-sender-operator.dev]
    resources: [emailsenderconfigs, emails]
    verbs: [list, watch, patch, get]

  # Application: access to secrets containing EmailSenderConfig API tokens.
  - apiGroups: [""]
    resources: [secrets]
    verbs: [get]
  # Application: other resources it produces and manipulates.
  # Here, we create Jobs+PVCs+Pods, but we do not patch/update/delete them ever.
  # - apiGroups: [batch, extensions]
  #   resources: [jobs]
  #   verbs: [create]
  # - apiGroups: [""]
  #   resources: [pods, persistentvolumeclaims]
  #   verbs: [create]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: email-sender-operator-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: email-sender-operator-role-cluster
subjects:
  - kind: ServiceAccount
    name: email-sender-operator-service-account
    namespace: dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: dev
  name: email-sender-operator-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: email-sender-operator-role
subjects:
  - kind: ServiceAccount
    name: email-sender-operator-service-account
