apiVersion: "stable.email-sender-operator.dev/v1"
kind: Email
metadata:
  name: a-failed-email-via-mail-gun
  namespace: dev
spec:
  senderConfigRef: mail-gun
  recipientEmail: flavio.alles@pm.me
  subject: "A failed attempt sent via Mail Gun."
  body: "Some message unsuccessfully sent via Mail Gun."
