apiVersion: "stable.email-sender-operator.dev/v1"
kind: Email
metadata:
  name: a-failed-email-via-mailer-send
  namespace: dev
spec:
  senderConfigRef: mailer-send
  recipientEmail: "not-a-valid-email"
  subject: "A failed attempt sent via Mailer Send."
  body: "Some message unsuccessfully sent via Mailer Send."
