apiVersion: "stable.email-sender-operator.dev/v1"
kind: Email
metadata:
  name: a-proper-email-via-mail-gun
  namespace: dev
spec:
  senderConfigRef: mail-gun
  recipientEmail: flavio.alles@pm.me
  subject: "A successful attempt sent via Mail Gun."
  body: "Some message successfully sent via Mail Gun."
