apiVersion: "stable.email-sender-operator.dev/v1"
kind: Email
metadata:
  name: a-proper-email-via-mail-gun
  namespace: default
spec:
  senderConfigRef: mail-gun
  recipientEmail: ${MAIL_GUN_RECIPIENT_EMAIL}
  subject: "A successful attempt sent via Mail Gun."
  body: "Some message successfully sent via Mail Gun."
