apiVersion: "stable.email-sender-operator.dev/v1"
kind: Email
metadata:
  name: a-proper-email-via-mailer-send
  namespace: default
spec:
  senderConfigRef: mailer-send
  recipientEmail: ${MAILER_SEND_RECIPIENT_EMAIL}
  subject: "A successful attempt sent via Mailer Send."
  body: "Some message successfully sent via Mailer Send."
