apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: emailsenderconfigs.stable.email-sender-operator.dev
spec:
  group: stable.email-sender-operator.dev
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                senderEmail:
                  type: string
  scope: Namespaced
  names:
    plural: emailsenderconfigs
    singular: emailsenderconfig
    kind: EmailSenderConfig
    shortNames:
    - esc
