apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ template ".name" . }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      application: {{ template ".name" . }}
  template:
    metadata:
      labels:
        application: {{ template ".name" . }}
    spec:
      serviceAccountName: {{ template ".name" . }}-service-account
      containers:
      - name: {{ template ".name" . }}
        image: flavioalles/email-sender-operator:dev # TODO: change to latest for final version
        imagePullPolicy: Always # TODO: remove for final version
        resources:
          limits:
            cpu: "0.8"
            memory: "256Mi"
